name: Python application

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      shell: pwsh
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pip install pyinstaller==3.5
    - name: Run
      shell: pwsh
      run: |
        set PIPENV_VENV_IN_PROJECT=1
        pipenv install
        pipenv shell
        ./build_win_exe.bat        
    - uses: actions/upload-artifact@v1
      with:
        name: artifact
        path: ./dist
